services:
  koi.webapi:
    image: lequocuy/koi.webapi:latest
    container_name: koi.webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=koi-database;Database=koi-database;User Id=sa;Password=YourStrong!Passw0rd;Encrypt=False;TrustServerCertificate=True"
    build:
      context: .
      dockerfile: Koi.WebAPI/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - koi-database

  koi-database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: koi-database
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1434:1433"
    # volumes:
    #   - ./.containers/koi-database:/var/opt/mssql/data
    #   - ./bk:/var/opt/mssql/backup