name: Build and deploy ASP.Net Core app to VPS - Koi Farm Shop

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push identity migration image
        uses: docker/build-push-action@v2
        with:
          context: . 
          file: Koi.WebAPI/Dockerfile
          push: true
          tags: lequocuy/koi.webapi:latest

  deploy:
    name: Deploying to VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Replacing container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/uydev/devops-vps/koi
            docker compose pull
            docker compose up -d
